config/routes.rb
Proposals::Application.routes.draw do
  devise_config = ActiveAdmin::Devise.config
  devise_config[:controllers][:sessions] = 'sessions'
  devise_for :users, devise_config
  ActiveAdmin.routes(self)

  resources :proposals
  resources :users

  namespace :api do
    get '/rounds' => 'rounds#index'
    get '/rounds/:id' => 'rounds#show'
    get '/proposals' => 'proposals#index'
    get '/proposals/:id' => 'proposals#show'
    get '/votes' => 'votes#index'
    post '/votes' => 'votes#create'
    delete '/votes/:id' => 'votes#destroy'
    post '/hidden_votes' => 'hidden_votes#create'
    delete '/hidden_votes/:id' => 'hidden_votes#destroy'
    get '/results' => 'results#index'
  end

  # Ember app root
  scope :voting do
    get '/' => 'voting#index', as: :voting
    get '/*catchall' => 'voting#index'
  end

  match '/auth/:provider/callback' => 'sessions#create', via: %i(get post)
  match '/auth/failure' => 'sessions#failure', via: %i(get post)
  match '/logout' => 'sessions#destroy', via: %i(get delete), as: :logout

  root to: "pages#welcome"
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  validates :title, presence: true
  validates :user_id, presence: true
  validates :abstract, presence: true

  belongs_to :user
  accepts_nested_attributes_for :user, update_only: true

  delegate :email, :name, :bio, to: :user, prefix: true

  def save_and_send_confirmation
    save && ProposalMailer.confirmation(id).deliver
  end
end

app/controllers/api/proposals_controller.rb
module Api
  class ProposalsController < ApplicationController
    respond_to :json
    before_filter :require_voter!

    def index
      current_votes = current_user.votes.where(round: current_round).
        includes(:proposal)

      current_hidden_votes = current_user.hidden_votes.where(round: current_round).
        includes(:proposal)

      respond_with current_round.proposals,
        each_serializer: ProposalSerializer,
        current_votes: current_votes,
        current_hidden_votes: current_hidden_votes
    end

    def show
      proposal = Proposal.find(params[:id])
      respond_with proposal, serializer: ProposalSerializer
    end
  end
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  before_filter :require_authentication!
  before_filter :require_before_close_date!, except: [:index, :show]

  def index
    @proposals = current_user.proposals
  end

  def create
    @proposal = current_user.proposals.new
    @proposal.attributes = proposal_params

    if @proposal.save_and_send_confirmation
      redirect_to @proposal
      flash[:success] = "Proposal successfully created. You will receive an email confirmation shortly. Thanks!"
    else
      render 'new'
    end
  end

  def new
    @proposal = current_user.proposals.new
  end

  def show
    @proposal = Proposal.find(params[:id])
    require_permission!(@proposal.user)
  end

  def edit
    @proposal = Proposal.find(params[:id])
  end

  def update
    @proposal = Proposal.find(params[:id])

    if @proposal.update_attributes(proposal_params)
      redirect_to @proposal
      flash[:success] = "Proposal successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @proposal = Proposal.find(params[:id])

    unless require_permission!(@proposal.user)
      @proposal.destroy
      redirect_to proposals_path
      flash[:notice] = 'Proposal destroyed.'
    end
  end

  private

  def proposal_params
    params.require(:proposal).permit(:title, :abstract, :notes, :pitch,
      user_attributes: [:name, :email, :photo, :website, :bio, :twitter, :github])
  end

  def require_before_close_date!
    if past_cutoff_date?
      redirect_to root_path, alert: "Proposals are closed, sorry."
    end
  end
end

app/views/proposals/_form.html.erb
<%= simple_form_for @proposal do |f| %>
  <div class="row">
    <div class="small-12 medium-6 columns">
      <h3>About the Talk</h3>

      <%= f.input :title, placeholder: 'It sets the tone. Make it great!' %>
      <%= f.input :abstract, placeholder: 'What is your talk about?' %>
      <%= f.input :notes, placeholder: 'What should we know about your talk that is not in the abstract?' %>
      <%= f.input :pitch, placeholder: 'Why should we pick you?' %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 medium-6 columns">
      <hr />
      <h3>About You</h3>
    </div>
  </div>

  <div class="row">
    <div class="small-12 medium-6 columns">

      <%= f.simple_fields_for :user, @proposal.user do |user| %>
        <%= render partial: 'users/fields', locals: {f: user} %>
      <% end %>
    </div>

    <div class="small-12 medium-6 columns">
      <% if @proposal.user.photo.present? %>
        <h5>Your Current Photo</h5>
        <%= image_tag @proposal.user.photo.url(:medium) %>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="small-12 medium-6 columns">
      <%= f.button :submit, button_text, class: 'button' %>
    </div>
  </div>
<% end %>

app/views/proposals/_proposal.html.erb
<div class="proposal">
  <h2 class="title"><%= proposal.title %></h2>
  <div class="abstract">
    <h3>Abstract</h3>
    <p><%= simple_format proposal.abstract %></p>
  </div>
  <div class="pitch">
    <h3>Pitch</h3>
    <p><%= simple_format proposal.pitch %></p>
  </div>
  <div class="notes">
    <h3>Notes</h3>
    <p><%= simple_format proposal.notes %></p>
  </div>

  <% unless past_cutoff_date? %>
    <ul class="button-group">
      <li><%= link_to "Edit", edit_proposal_path(proposal), class: "button tiny secondary" %></li>
      <li><%= link_to "Destroy", proposal, method: :delete, data: { confirm: "Are you sure?" }, class: "button tiny alert" %></li>
    </ul>
  <% end %>
</div>

app/views/proposals/_proposal_list.html.erb
<li class="proposal">
  <h2 class="title"><%= link_to proposal.title, proposal %></h2>
  <div class="abstract"><%= simple_format proposal.abstract %></div>
  <ul class="button-group">
    <li><%= link_to "View", proposal, class: "button tiny" %></li>
    <% unless past_cutoff_date? %>
      <li><%= link_to "Edit", edit_proposal_path(proposal), class: "button tiny secondary" %></li>
    <% end %>
  </ul>
</li>

app/views/proposals/edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <h2>Edit Your Proposal</h2>
  </div>
</div>

<%= render 'proposals/form', button_text: 'Update Proposal' %>

app/views/proposals/index.html.erb
<div class="row">
  <div class="proposals small-12 columns">
    <h1>Your Proposals</h1>
    <% if past_cutoff_date? %>
      <h4>Proposals are now closed.</h4>
    <% else %>
      <h4>Closes <%= ApplicationHelper::CutoffDate %></h4>
    <% end %>

    <% if @proposals.blank? %>
      <p>Here is where you will see your proposals. You have not made one yet
        though, bummer! Submit one by clicking the big ole button below. Even if
        you are still drafting out your proposal, just go for it. You can edit
        it at any time.</p>
    <% end %>

    <ul class="small-block-grid-1 medium-block-grid-2">
      <%= render partial: 'proposal_list', collection: @proposals, as: :proposal %>
    </ul>

    <% unless past_cutoff_date? %>
      <%= link_to "Submit a Proposal", new_proposal_path, class: "button" %>
    <% end %>
  </div>
</div>

app/views/proposals/new.html.erb
<div class="row">
  <div class="small-12 columns">
    <h2>Submit a Proposal</h2>
  </div>
</div>

<%= render 'proposals/form', button_text: 'Submit Proposal' %>

app/views/proposals/show.html.erb
<div class="row">
  <div class="small-12 medium-6 columns">
    <%= render @proposal %>
  </div>
</div>