config/routes.rb
Proposals::Application.routes.draw do
  devise_config = ActiveAdmin::Devise.config
  devise_config[:controllers][:sessions] = 'sessions'
  devise_for :users, devise_config
  ActiveAdmin.routes(self)

  resources :proposals
  resources :users

  namespace :api do
    get '/rounds' => 'rounds#index'
    get '/rounds/:id' => 'rounds#show'
    get '/proposals' => 'proposals#index'
    get '/proposals/:id' => 'proposals#show'
    get '/votes' => 'votes#index'
    post '/votes' => 'votes#create'
    delete '/votes/:id' => 'votes#destroy'
    post '/hidden_votes' => 'hidden_votes#create'
    delete '/hidden_votes/:id' => 'hidden_votes#destroy'
    get '/results' => 'results#index'
  end

  # Ember app root
  scope :voting do
    get '/' => 'voting#index', as: :voting
    get '/*catchall' => 'voting#index'
  end

  match '/auth/:provider/callback' => 'sessions#create', via: %i(get post)
  match '/auth/failure' => 'sessions#failure', via: %i(get post)
  match '/logout' => 'sessions#destroy', via: %i(get delete), as: :logout

  root to: "pages#welcome"
end

app/views/layouts/_footer.html.erb
<footer class="row">
  <div class="large-12 columns">
    <hr />
    <div class="row">
      <div class="medium-6 large-4 columns">
        <p>©2014 <a href='http://burlingtonrubyconference.com/'>Burlington Ruby Conference</a></p>
      </div>
      <div class="medium-6 large-8 columns">
        <ul class="inline-list right">
          <li><a href='http://burlingtonrubyconference.com/conduct.html'><i class='fi-list-thumbnails'></i> Code of Conduct</a></li>
          <li><a href='http://burlingtonrubyconference.com/diversity.html'><i class='fi-male-female'></i> Diversity Statement</a></li>
          <li><a href='https://github.com/burlingtonruby/proposals'><i class='fi-social-github'></i> GitHub</a></li>
          <li><a href='https://twitter.com/btvrubyconf'><i class='fi-social-twitter'></i> Twitter</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_navigation.html.erb
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><%= link_to "Burlington Ruby CFP", root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>

  <section class="top-bar-section">
   <ul class="right">
     <% if current_user %>
       <% if current_user.admin? %>
         <li><%= link_to "<i class='fi-lock'></i> Admin".html_safe, admin_root_url %></li>
       <% end %>
       <% if current_user.voter? %>
         <li><%= link_to "<i class='fi-clipboard-pencil'></i> Voting".html_safe, voting_path %></li>
       <% end %>
       <li><%= link_to "Submit Proposal", new_proposal_path %></li>
       <li><%= link_to "Your Proposals", proposals_path %></li>
       <li><%= link_to "Your Profile", current_user %></li>
       <li><%= link_to "Sign Out", logout_path, method: :delete %></li>
     <% else %>
       <li><%= link_to 'Sign In w/ GitHub', '/auth/github' %></li>
     <% end %>
   </ul>
  </section>
</nav>

app/views/layouts/_notifications.html.erb
<% if flash.present? %>
  <div id="notifications" class="row">
    <div class="small-12 columns">
      <% flash.each do |k, v| %>
        <div class="alert-box <%= k %>">
          <%= v %>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Proposals" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: 'layouts/navigation' %>
    <%= render partial: 'layouts/notifications' %>

    <%= yield %>

    <%= render partial: 'layouts/footer' %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/layouts/voting.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Proposals" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "ember-app" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div id="app"></div>
  </body>
</html>